# Branch Protection Configuration
# This file documents the branch protection rules that should be applied to the repository
# These rules ensure code quality and prevent direct pushes to protected branches

branches:
  main:
    # Require pull request reviews before merging
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
      require_last_push_approval: false
    
    # Require status checks to pass before merging
    required_status_checks:
      strict: true
      contexts:
        - "CI/CD Pipeline"
        - "PR Validation"
        - "Build Check"
    
    # Restrict pushes to protected branches
    enforce_admins: true
    required_linear_history: false
    allow_force_pushes: false
    allow_deletions: false
    
    # Additional protections
    allow_squash_merge: true
    allow_merge_commit: true
    allow_rebase_merge: true
    allow_auto_merge: false
    
  develop:
    # Similar protection for develop branch
    required_pull_request_reviews:
      required_approving_review_count: 1
      dismiss_stale_reviews: true
      require_code_owner_reviews: false
      require_last_push_approval: false
    
    required_status_checks:
      strict: true
      contexts:
        - "CI/CD Pipeline"
        - "PR Validation"
        - "Build Check"
    
    enforce_admins: true
    required_linear_history: false
    allow_force_pushes: false
    allow_deletions: false
    
    allow_squash_merge: true
    allow_merge_commit: true
    allow_rebase_merge: true
    allow_auto_merge: false

# Required status checks that must pass
required_status_checks:
  - name: "CI/CD Pipeline"
    description: "Main CI/CD pipeline with tests, linting, and type checking"
    required: true
  
  - name: "PR Validation"
    description: "Pull request validation with coverage checks"
    required: true
  
  - name: "Build Check"
    description: "Build verification and artifact checking"
    required: true

# Quality gates
quality_gates:
  test_coverage:
    minimum_branch_coverage: 90
    minimum_statement_coverage: 90
    minimum_function_coverage: 90
    minimum_line_coverage: 90
  
  code_quality:
    require_linting_passing: true
    require_type_checking_passing: true
    require_no_security_vulnerabilities: true
    require_dependency_audit_passing: true
